---
version: '3'
services:

  service:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.${CONTECO_TYPE}.${CONTECO_NAME}:${CONTECO_TAG}
    command: metricbeat -e -strict.perms=false
    deploy:
      mode: replicated
