##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.heartbeat:7.8.0 AS base
USER root
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN rm -rf /conteco/repo
COPY ./ /conteco/repo/
RUN chmod -R 555 /conteco
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/usr/local/bin/docker-entrypoint"
COPY ./conteco/configs/usr/share/heartbeat/heartbeat.yml /usr/share/heartbeat/heartbeat.yml
USER heartbeat
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="heartbeat" \
    CONTECO_NAME="base" \
    CONTECO_TAG="7.8.0" \
    CONTECO_BASE="external.heartbeat:7.8.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="heartbeat" \
      io.vcweb.name="base" \
      io.vcweb.tag="7.8.0" \
      io.vcweb.base="external.heartbeat:7.8.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="heartbeat.base - ConteEco" \
      io.vcweb.description="The ElasticSearch HeartBeat base image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.heartbeat.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
