#!/usr/bin/env bash

export CONTECO_LABEL="heartbeat.base - ConteEco"
export CONTECO_DESCRIPTION="The ElasticSearch HeartBeat base image."

export CONTECO_TYPE="heartbeat"
export CONTECO_NAME="base"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="external.heartbeat:7.9.2"
export CONTECO_BUILD="image-base"
