---
version: '3'
services:

# START SERVICE metricbeat.base
  metricbeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.metricbeat.base:7.8.0
    environment: []
    command: []
    volumes: ['/etc:/hostfs/etc:ro','${CONTECO_STACKPREFIX}_metricbeat_volume:/usr/share/metricbeat/data']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${CONTECO_DC_METRICBEAT_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${CONTECO_DC_METRICBEAT_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_METRICBEAT_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_METRICBEAT_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_METRICBEAT_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_METRICBEAT_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE metricbeat.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_metricbeat_volume: { external: true }}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
